version: "3.7"
services:
  dmz-server:
    container_name: dmz
    restart: always
    build:
      args:
        - APP_ENV=dev
        - APP_NAME=dmz
        - DNS_RESOLVER=127.0.0.11
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
      - "8000:80"
    networks:
      openresty-network:
        ipv4_address: 172.177.0.8
    volumes:
      - ./nginx-prod.conf.tmpl:/usr/local/openresty/nginx/conf/nginx.conf
      - ./openresty-admin/public:/usr/local/openresty/nginx/html/openresty-admin/public
      - ./openresty-admin/src:/usr/local/openresty/nginx/html/openresty-admin/src
      - ./openresty-admin/.eslintrc.cjs:/usr/local/openresty/nginx/html/openresty-admin/.eslintrc.cjs
      - ./openresty-admin/.gitignore:/usr/local/openresty/nginx/html/openresty-admin/.gitignore
      - ./openresty-admin/index.html:/usr/local/openresty/nginx/html/openresty-admin/index.html
      - ./openresty-admin/package.json:/usr/local/openresty/nginx/html/openresty-admin/package.json
      - ./openresty-admin/vite.config.js:/usr/local/openresty/nginx/html/openresty-admin/vite.config.js
      - ./openresty-admin/yarn.lock:/usr/local/openresty/nginx/html/openresty-admin/yarn.lock
      - ./data:/opt/nginx/data
      - ./html/swagger:/usr/local/openresty/nginx/html/swagger
      - ./api:/usr/local/openresty/nginx/html/api
      # - ./.env.dev:/tmp/.env
    env_file: .env.docker

  dmz-redis:
    container_name: dmz-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - openresty-network
    volumes:
      - redis-database:/data

  dmz-sample-api:
    container_name: dmz-sample-api
    build:
      context: .
      dockerfile: Dockerfile_nodeapp
    ports:
      - "3009:3009"
    networks:
      openresty-network:
        ipv4_address: 172.177.0.10

    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./.env.nodeapp:/app/.env
      
networks: 
  openresty-network:
    ipam:
      config:
        - subnet: 172.177.0.0/16

volumes:
  redis-database:
