apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-images-access-api
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgBabK+Kb7GZSaLGQwceFaArr+scfxXByk0A1+ThDAprdgMRlIpV2stc4t5QPVkNAg1QOQkUderzhqlyiCjVMd/2yNi0Jn1m+VQjwU/GeB7uceDdynOjyBO9R4Jz3nREgArAeyLZ+lJaR4Ajd7xQB5tgVNYjrDe3PmbdGtVA0nkzs24RpbXmE+L6vG/K8ufBs0h0TNKausXNxBH09WKoH7rIj8ZG13c8SG15b3d8/vxTIDPjOYk1h+E1FvwrBCh6P7pYNxZDK8/JTYKxS3DVShJIBfq3U9zxuHVLMZghdiFMDXIfijHLOjG3iMQXZoGnwpCd39nuWfXH6R+ST3AIEdNcPazYOesK0fu9ZzfL4fWd0kcujRftJrSIYbaUNBKSezYZsCQVhFZfAS5e6/6ah8SkJuwTUfDwJh1Qxl2NNAJqTE2WJbvtSphOQzEKHfWI4/RLfG2YuWrSV1qSspg3Kj1Tte5JsOzWgWFzCQUOxq6IeFzqtXkA1WbcE3DWQ8PW8Kf+O8UO7FC8Ad+eMIyzKuzJKhqr37LHG4QXQWCelnCQOxaIgkoArYaoJgO11fSu2iFguLuD0YBnmmGP59OUkhex/L+m3MFVFJMrKN7eSUiqEAv/gX866ys6/RInR4qGe2Ur1RXWjODvjhu1Zu1O3KSFegcqhZeFKSJeSXLsqbI5/sBVPfnzn8d8wh+R91ZCA6tREW7SNjbn9GcsvUJnVngOlmqD36C71hQ5ZnapS/5X/cnBnI5+wloxtTYQXhY7THSOT68WErN6z4jedffyt6K2vxadJiOWfC5pmdoejEDEaDHrvGc+h5Be1eU6UIREMqb1JgPj3MLz1pe1nMBhUbE0fxejtXN57Lev77GLyne/NajGewN441EM8YMC9zCe3ghAzWLRaMCKXPHuq3e3DmpJBXQNGhyvaqVTHH2qBk5x+YFPL/fJ2uxREIfzmtb5Wi3Vu4SzNeJrCONogD7+ZDl1xYMShLJDNIjp/vmbjun2kxCUqeUB
  template:
    metadata:
      name: nexus-images-access-api
      namespace: prod
    type: kubernetes.io/dockerconfigjson

