 - name: Update and upgrade apt packages
   apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 
   tags: [ubuntu]
 - name: Install dependency packages for installing openresty
   apt:
     name: "{{ item }}"
     state: present
   with_items: "{{ ubuntu_packages }}"  
   tags: [ubuntu]

