# Default values for dmz-router.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  name: dmz-front
  version: 0.1.0
  description: A Helm chart for Kubernetes
  keywords:
    - helm
    - chart
    - kubernetes
  namespace: test
  dns_resolver: "10.0.0.10"
  dns_resolver_ns_primary: "10.0.0.10"
  dns_resolver_ns_secondary: "10.0.0.10"
  api_url: "http://dmz-api-svc-test.test.svc.cluster.local:8080/api"
  redis_host: "redis-service.test.svc.cluster.local"
  target_env: "test"
  target_type: "front"

persistentStorage: ""
storageType: ""

secure_env_file: "AgCCa3GPtK9gWWh7jYs3puJdhE2cB8jmby3bFfeUny8HxlvazuSLP/SSq2c0SWAKugHJ5qMJr+LEv8vfKmkV6ZfqrgxqUUXIEGCGUSQKSszc3OkZItSg/8DqBH7nZCVxHG8jWKOesghy8J3L0M6JJe2eR2wHviGjSpVo1T7uR1ck2cq+8BWfR2aTC5Fs60oBH0ujZHgON/jRvff3dGwOuQ1O8Jf4otuKlNrbIY+WNyKAbpfVAkoUXZt3tIbrPEOICHFM3hK1rUailr1D25plofplc2JJ7h9h+YFSwjxaZbvs/O0O4OM/9C4Qjb65WATljJKJkiT4IhIB6MDlOH0esAw7tvMYY3uwmWfnvP0DMVa04ZaNnp5hMg0P6X6ljM6Va3N2xh9+drVz9dfQJronhoppsPLQO4ivAXoUcX5sH5yUlCCj45q4dykdVEhPbqvGFmUaOTtzSaGP7MNptgBu5Ao4gU6ZLUNbiEW35ZWY/YZl7ByA5twPTLffuQ6gfiUThNKHgTjt1G5MUss1ZRl5ZGmwnKKUz26QaJtkKDELJdJN8mLi2D10QLDFzBCgEXjuykFQIQn3heGvWgspDU3oWoWMe25n6DuMBcewYOc1abLoJDgOyygw1TgOwLcfT4jxpqCQsjL+NuoNNEWo3Q/F9q1rz+fx/kPcXwdFRm186NkBeZqp2nlJzKkS6SXdHVF3sTwvmcaiaLP9WQv4Lgq4+4gTDD/BQqEbS0vVEDQby/ZOsX8mVjrW1mXHi/9xt/XCorRhhg0eFSmsMAYcrkOz4K4zpd3oXqIW2MKKg4UmibB34Zn6DSd4I01mcmM1IeK7Oz6acNgz5plFhln180ItScjWmHvS4a1kwPZfZG1ss+4yqYvMD1IKVD/3+Gjj1umqzExe6n4F8tgaaTnWf7uDAIru/DHkJN5/Oy1XHmM9GEtJig+/hTioFc8O03LfwjTA1YsqCfAfOoYl7g5detFFeABdqxtiW9vSjIdCPta+w3P/Pg28SY4lCJNTARucois8YhshCJiWPU+CIhG47Y0JPcSWzwdoid9v9ZaK0ULZBQ9nAJC4lhnDeBxyQo/5ZWqUkjGFD2e6n802mSBriPFodJNTMQUsj7s5H59Hp5sEliF+UIbFxEbc/SzPtDiX1/phWkXl4QQORgGTuDLWBgo+qdN9Y9/AlHsuHM6/Zl8xkNYSY/mnaoYDM+zLobKDB5yj6JR1XBKECOImt+/ESxe0BcL4uxyWyUwy1QP0bwN0mW7a/LZmKMJPAR7QLvcG8TnoyudQws2yvcAzXK6+aoC5COc6Fft/NuPIlZ6JlBtDuOBa7NeLjO4="
regcred_nexus_healthdata: "AgCIOc306vQZRRoBs4Y+mQfvFpn9HdKecSNqKMjlJ0B55V63pXuWrGW+Vghz3ITBhaB5gflFNxvPEVR8r7/3xDX7hX3l1+aOtF/i69ehrAs05jeLOryQmybTm5FTweQTjCEkwLgrjjDK/UYcC5YeoFQD0V5DZKABpZKzKUazj6g5wmeHHN3DEl6Zn/Pd3jFslwGNJIpS7tlN6zHwN+orntfDrYNlzuAxHTE6CO6H3A/v3OPbU53MV0xXzYkZcG/l9rLGlGP5cj9hCwir2ipENQt2HFuPh4uBTyLGdRkERaEkdMOaZAo/tRgl2dTg/jRki4ES7wOQ3bDou3OrcAOGv/Y9UmAH5HJRaHcszmX58/pbqgKDJYKC+QNm8PQ7LuOYWORQtb947wPonx7acUVLr4VR4ZGt5hCRBruIxFKPkoqfNz5yvJ6CypzAMdwfBdPmASUc6R4dNlWSTVOh7F1DLV2nnPmMyoc/cA2Yj9IiOPPcmvvhDS82RqkVHWe4v1h5iR37mOQG/nTrmWiqIjSwuUpD/C5ZTkq0hKTvLDBEY6HXNtPLU1TCO7kJ5Wv/FzybbSnA/7eTGIJg6eHVCQJty0pPZ5D/xjMnTYPu/CEeBzfc7T7y6wVcbkFkq48BDtOAm/vahn2Pu8S2I35UVVIp/iyyl4LnywU64ySvpeNJZZU+hLdGPOmhXy4T/tzdQIFKlcnrqSK1+c+oVtoJDb1ouuPWLFLqbA+0WWiyO0eJUJLGmbFXBH1f4txcQKHeLKpfyGtakJOvbZwO5KA0/XhYOsBW4Wx9jKM6no4Ds6AUmpF5+0BbvdLzFohoRMtJu5WAKhwQCwMZdGGPUOkp/b3pWDVEVWe6zO/qwW+ntE9Asi6Pxq/3SFbCbKWre7XjgmPMoocUmAWyBkeZwrvH6ZYGyx1upjtnMq3ut6i8Qixb1Kf1mMFRFmiCNt4rgg/ZO6pjHSWsfBMKz2WBvCNJgVDAdxqTikauIhTY6QE3YPAa4jUoxHjg4D6+"

tlscrt: AgBU50JhejuHLntmMq2Bjn3ZiD3Fxb7VGGAU8yu5z83CRpU/q/R/TYMrn7fXxNVDAn90UfDLe7JR99oyhVKSiOKwaArJhQgGOHPYcu2C/hOFeAwykE7pzxiLczRueTeRT6fddYFI/SlCWW9F+mqFMVlN5FrnMsdhnVx+RaRS+lJ1glq85/dkmed6NsmcsO2EN/PKCkg5SAKmBeMcup4RilDucywc6N6LkcLxz/e8kfOaeZkRiVp4ahuTidaHNgbOWFzuWZOoqOM7kzA3La8qe4IBFr/Knr5K8jqjKgTwpSyNhAaY13h+14JzaBe9ir9ypd2J06/EO6re7J9mv9WNPOhufCXoE8tb/R7JjldD6DWvPbWlnM4FPYitwcrvlUAyfEcs2CGyXvxVQzjJ4Vqse9j9g+4iK/Cv3Y2HCgHyboEL8kpn/OLUZJ5zpSu4517I2lwFdWu6+WpKdBLvDxTJ5Lz6s4bIIR92CLogKi/LClqCNOKZiDMy2vxWutHknscFVQc8s5TVioR3dgtnCerLT6HHOtJ+py/XtbamVl9PJgDWf/+WkaXkRvIs9pQZs0/hfx5B2ge+m6bzOLBn1POyi/EwEh+RkcQWrAHcUCEq/Jia2ELDPpLdX19UO4BK2W2+4E07rFxPV+RrWPrqHcBrUjKOOCu/wm8w99SlGmf7/uWJ0CPEyAF981ZeqmlKNCpiPMvk3nVDAjBE2FRxdFI9zTGFs0vF8v8oIhVXB1RQ1LuuGZ06I7ZwDVjj2Zvlk3Ac53NEyEu1S+ziMlAx0FU5TMAQn36EBf1r4yWraitnA4+CJvwyexTb52B/gO1Kt4hWsS7b6qXV1V593q03JcAti3eYhRwvn1YjCEOXbU5D7VOou7rpZwa5r+ZBfCINK0OC5nksDGoHMPLvDMFRbs25JIEuJZD92P+03npnMKPEDJ6BIyH+nT6t9TT/s3NoxKXGCIrd9BlQU6F3kvljz1igQJ00bJaAjcsQW0MBndJnhwaimU035g2M4/Yr+DsmWDfMu0/oL6BOOuG+l4zkytjKngq+ROUKNl3WFWElNbfhBMi94ET2xeeTmf3oMghRnDyForLNh9E+o8dSwGHYg4V9UpPN+Q0rjFjgZ6v5+1U6jG0zhVmE579uqZiNR8lUsKy57mDPm2rnNT+nh0gmxxuU5j98waKfJf+xCVuSOcvZJQ6ZElY0Jn0Xb+klbJEwdEn6niQ1zz7LiIzscAGSWdY4EWJ9nDzZpAiYzlPPHMtj7Fa81RweQ9JLvhGzIgQ0/q34yUVRgELrDsPgKRYrn8uTC3QewGjR+ywBlLaiPJzuks2JgcujNKOUK78GBNxLe62emDhKD0STHrJV5TltJq4yby8H6PIrjeS7VYFHig+wSdviAP2jjKdxOloOgynCCxUZCCK2RWzwmmtQisgYoOhvvDzHfqnbDXdbu5TvSX8bfNk1cT7oxAbdYLBUJ/PUYgMICi/swh3XmWOVdGbvkjZ+UQQk1VnyCszdCqtm2xyM2tyTdvQA8UkgPZxEshee19p5gDnt96OmOjrIvWXMRyDGX/0DHNTRDJOOptLcAq8yqAkHkIIZkux4EQHz+H7RDcfZ49DGTsiF4wKNgEVCkSGVxFyhHjjVjYHbKR+Fj6Sm6foCLCjMRpIfSfiNF5OuZyBtE+pS67TqtwF4Ve5nS44LRFLaF3U7yOwJrWqWlNKDMYP9pcWfjL9xUyr0eNiC+Fuyr2Sa9KBV2vTEjhpfNM8rHzxvX1qlcMEIFR/925Yw7/rDd5Avv4oEXMkH8QMVcKJgI9JFmyV3DKMphSxcb9IXQSdGJL1kB3m2AnQwk1TInzCetfoe5/u98tmql8dkSpec7voTm2xJ/gfFbGK+8qOpx5J9L/GtI7/1zrHCaFtM9P+Fvjs6OjTyPfIkiq+3mhjfQSQ6gqQX5fl0iztNfHO6O21qJIIA2YltvHvkrDs5EVCrcggDTRUFMMQBI57mnYlK9fxw4KvexOw4x70XfijGsSuYsGlhlSqpvpVFW+o93WByeIZHYCEzs1c1v7KB+ENyOfeGoRusxWMi6md2iY+96ItJ0iSsXjrVFC/82XW0Z+9Ts/+Lnx3CC9vUpMBcw3mtQL08OrtarWii2BQZH3uqmbiDFNbgk54Smw1J4IxZtj81/bwwJOWeWZdZIkRcc5B2WUhBimWK5ZSxCmPeXuYpmG/udahNc++J1V3v2nrdzrKMe/TQBTKxrgq991kDHKt3qsL1s/G48pesntEU9lI1E1NsFyt1pQ+WuTbPC50McWnqAap/N/FOHLif0HiUNEuTuPzH2AW1EDfEnMuPw0QVLxDCeUt03xw9NRlLEYSlRypqS8CsvxzNfe6JIUc1kam9YXhseAFmHblFkXwy3bHup7kSVxszvycTgJYS3uw37JW0BJmqEmpLvPgEJsRuleBtH04z5oSplTYHHdv4jOsav0stvzYHy80h7ji3EepJHaz8st+hRxs1AecIvEXYzyX05gGHHAfRrZADpIb14SxfC7Q5juC3W/YN0kGLuzAM3pfaqVhGLAi2BRlju+JA5Jt93QunfsStTv9onzmZVhPDN9aV+obGmeyUGl9FHn423Upb23kb/p3PF1ndZXGPdBXmk9m7tnw/IzsvrG4yPW6RjjH40cTq4UEMpnAVOCz2pxsNtLqlxxoWnTsEHJx+9P0K+sMYqBSKvQjOe2aik+1d7Tkwz2okdvzc3pGGGAKPz0RRPSsbnQyNbagWSFcKphsoNKKoOSZCB68/RfTNSJ/EFQnGrT+04oI2ZQ/1tsxn/BYb701H+63NfuGPJRw10IsYeThHemZwLdTR4n3UcwckKjMj0wa/8BjlKjWX6f7Qq4ifwctx3nGlVaj5M+W53bxv/VYCnEyKT3FA0CDDNv5LXNvkseDzggUdKsium+wpkvzkPh5BOiDY1aUbpfy6LmPnymhnizw4NvmnSgcH8P8HX7huOUuLO9v6VVb2HoLq569yEPMuMHGfTBWaRXLKyV6VJwEY8+5uF/tIkhskrBVC/d8ezq7IBqs7g54JSAlXJ7MExLWPYGkUjUQQ3qJ9+h8rLNLrm7ibutJBpCBNrJ0g/JI2sRkENgU/PSlFlWPT/oZzkh0pPvMGu1Xz+1nV+lo0ykEcCz8Foa1FPYnk0kW5cK6hV0dotvxlVFfhd/4apCRSsVr7jsV2DcxdGQXop481ld+ydMh/EExXEofCEmAKSUD7Y92DQE6m5VM3BzkpFpRFlhZkeq0PvcMdDdXUsOeNGc5zGQWMXzDqOFPk7mcY9dmMk/zQUE25vprr4Te8pjUTYQnAb9TiglBGPp7IhHrjD5My/H+CnXcBthTE1T+WmAljnmR6EBnWkNq5mCKgD3xD1RSnGx/116S7SWJSvYJmyZGNYhFAz8Ae/PKvXJ3zVXO/MsGOV1f30nyCGxtvOKzAdbaMrvB34MgYV9ukuYMH4POZaCXNySImf3QVGgLRXTzldDPwewBNFQmRX6mVz4fmMamuRCIXVGIKjHBVhSFBwFOYJ46iMWwcwA1klQrNmd9oqSFklUA0l6KprIb+QN6KqTEjHIfpUHiDSWROkXwGR4/OVem6ac00vHNjGNwzGvNCdl43QrgpN6Vp5WZHG/wLfyJcc/ZkdcmvQMPstPUxLdYHoFd2bWT7a1Y3h3zxx+1ZNeTxx9+3A2TSkYpvE2Qa
tlskey: AgB8akgirUOf0DLQJNjExsSIDexwyN4X//R35Eo4bjDDciLqVMyqUBpf28ghN6wts9ZEygoeFbHSeTQLbicwmMPHnVGsFIEilPPI7BTkOq6G+OourPwWbSfXNG5qpoWxQ8qDMvnKgoBiq6bK3hAb0moLakPsW9kyuWUWYV3oB1+Ox+2UW8V9XvbUliswYYangDOvSTMTLUup1GRN7FYvHX5QoQ+cN5/P80YX3yZfR9VmK/prm4EJYfgzWjolrLTG3Byhvj1ze9LmTonRn0iT0MvLxWHFrS9/vasEV3d7kOq6ed8FqeTc8i5PxaThakv3V9A0XMcOfIgPhN5OstShcOopvfhTQ2iJw8QkrczuAjPkGQslq8XHEz4Xrie139SK54VlwBx4sb9RDuaM7qzSrJ6fGtRB0KAoF/QYjfdUFam+TkBHv832qq0F8MPVFc18w+k0mKAlAYL+2b3ADg6Q9lHJJRCD/2vAjLpyOvYS+Q0dU6gibg56ffjEl7rH48ymp2QobqKOfjILkmSDSBgJSRukKou2Eu8bUUYvohZQDSgx+5p8VbuaYk+xSmphRiCREV2toNXDQabWAykOk4UyE7z1zg+rG+8xqTtk2e/d9c9p+bxCxN0bHqIDK9r6YZDhAp0RKuxY2ji0S0PhiC23PR8Q6BjP5PtYuUWHNaqu9xX9d4Eoh7GjpiGbKKly7+ZDmXxXeQM/q9Zr2Na2f8IundECqfTEPAq3Zkzch79odajnGeMvASW5r/t5R4BbC4KiFwmiLoX1LHmn2mVnzTXaAzIr4fnxiKdXvmApLUdQCR4ewQzoRN3FKy+UdiRT5BjnEXwJJ1d3ckGuRq14jy0gEjH2ZaiePnb2Pb4y0/v5X2J+vcZI4IP7as5S2LN+PzFuTfUH9qNwYfYswehJlYYYrIXZKxCpefBJP2HyDoq+hZUmyiY7EMHbIJc38rXnSPOXM7kr3x6UWeuE2jbzyrA+y/wx12BgHGeuMQGdQTL8Dy7Ziv4sHjoAfTz21uOem9PuWNeMbn0OQSrUUbLG/QZCTqIPp63dPz/EtnFZazUrUvsAui8tKLUAfRx0f6336NyhOAM7W2cWXAa8uhib1wldH8qdmnKYa6Ik53PDiJ1uhi7BR/i4+77uWU3xyeHl2BNVC/KF9tftPSL/ag/PGBjjTLgpR20jtjcH19s7l5TzwfFpRI7Rv9l/xtrRB2q6HkSCqVZnR/t1QPZuF3Aiva5iyrMbsxiSWn+/UHzwf+twKyeKaZ2IVAnvujjqrFKFF93BECLF1tMrkgLoc0ALPZq2D683QZTkBtq2Kyoc8Y+sRJ6OrufqbwDA93PPCmBo6jUQxQ3Pn7S0RamboyE9hkZSJm0GJsywsgpdrTGFPLp7mooYqdxZpmb3KyH6UfxNJSebAKNOhl1v/yYEURldr2m61LtKsOsaCeisg/UUT9Dg2Ewq4vb2fZgt2t5ECO4PsV+AovWDnw6eFAA+j87qlkj/pfodaSGR0hV1qVE7cL6OZnzOJl0WHhRJdnYDmTF2c+PGNkj/D6DmycqbN0xpTsm2zKsIsftK7lY4lgMyhpnm1jmBLkwXWuBTF0mPYZXLhp/v6L1tmXfpLaucTdhf5fmnRyrsLCAVILS4hq7YGbxnJMY3hc1tfaBbyN2Ws2nJwpkmZSjN14roHYB6Qt0/mM0KBf3GpCkfiG/0F6JY27zztVRQ20iBYkwH4raO36TZV6Uh3tuIPbMNl+lnGghuFVOnX6e73H/GjmiH1I66daErTiahOWFVrVDz8H7ivH6+rh7w+jX4qAm5CNxyJE72t4sCunZYkCXzrBnRfAQUxzX1TENtYJu+LCZuOnhhBWzw26jqLKnJrNCnrobLCFEVkYswQdGdPurOxS8ngaSjXfqt+W6v0wLs///mbV6WUFUm/5kJ7itpxxtbUNPifSLxCm1FQb0lVypdOAdugzpVB4s2UZiWAPDsRIQQciev56qRCM0kzpSzDN8k3qtzNJgvjZ7sYVfwN6UTZdQmSAVqHon8sUcKOGMpEhO0SVWMqvN6Ge8JH73qbY3gNwfbKxOLYOVVe4PaQa9vtXyO3FPMMtrkD9I4TLLhmHmJNpNGwaqpdxoUt+XhHIvn4Un3krAKp0C9MzLRQHNbds0FjO+lPMk9Uh4HvxD3sbu5lGR6vYFgCZoY4JEM1IIv7Kh4GeQgvCSMMUfc1lPaNC0/dxyMjVFv4Snuea9VRHrj1PegsLq0zo1aBlcRxDLY6uJEhfTMQGqgP4ywOzCtc343iXJ991jKWDdoK3QLfCFlQtqPXwamOYElCh0V3fi+5HOPScZJ9iePxn2qmITWPHyHceX2AT0Md3xAZNgosyDOgFzEyZwpxJFXbdXExZNULHdl6yiR0DRIMpG8YwljcYGqscO3fNMBuzo7NLGj/eoLDLhYYIS1QoLUUNdBFlbvtk6dIwRwhvunOtifsAXgXaTBpSXaje+DkSZpb3oG/XbyEe53i6bgXMdWcQeJGegymkGTvjWLrP/UCM+D4dceygt85evzJddJbDvz9q3W3wHYhQWG38XrV6ke1nrdaE3ZhCbBgJ42mJwEQU1J/mKM3K/qB3QlTHyfcT6Wcu9rKQMAJ2m6gMKtw0uWajNjjEmi/4xk9aTDmww2IXW/52q6MqgMZ/HxBe7cbn7mT97+/ysIUkUyDHHOUFauQvLEtQW4ryz9O7VUDPoDEzvavMTmM23Vuw1cf7iEzoRxsfo5vuqD/e56jZZMUYL0zLFucBXCalpppSXQusgXIuthIbqH7XitOhKLOnrCwuRnQ57TPbue5ZMzGv8LLyZJn+e3+zpd8NEhhI3lGpxpswm9fhRKNcV7htNhK9e6g1DFf0x85zzY3YQYmv8DJ6ihPUOTzypIGZbaHJlB3EAe9QCi4HrdKAAIDlkenwcc4oZSWz+BnINIxTrJ3Fs1aoQUG/gLIzpvOTYgq+U/9zt3HK/YqBO4H8I4hA==

image:
  repository: 192.168.1.193:30082/dmz
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
- name: nexus-images-access-front

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: test-front.kubes.dmz.it.com
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: dmz-front-svc-test
          servicePort: 80
    - host: front-test.kubes.dmz.it.com
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: dmz-front-svc-test
          servicePort: 80

  tls:
   - secretName: ingress-tls-cert-key-test
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
