######################################################
# Secret: Create Multiples encripted data
######################################################
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-images-access-{{ .Values.app.target_type }}
  namespace: {{ .Values.app.namespace }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.regcred_nexus_healthdata }}
  template:
    metadata:
      name: nexus-images-access-{{ .Values.app.target_type }}
      namespace: {{ .Values.app.namespace }}
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ .Values.app.name }}-ingress-tls-{{ .Values.app.target_env }}"  
  namespace: {{ .Values.app.namespace }}
spec:
  encryptedData:
    tls.crt: {{ .Values.tlscrt }}
    tls.key: {{ .Values.tlskey }}
  template:
    metadata:
      name: "{{ .Values.app.name }}-tlscert-{{ .Values.app.target_env }}"
      namespace: {{ .Values.app.namespace }}
    type: kubernetes.io/tls
---
######################################################
# Secret: Create Multiples encrypted data
######################################################
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ .Values.app.name }}-secret-{{ .Values.app.target_env }}"
  namespace: {{ .Values.app.namespace }}
spec:
  encryptedData:
    env_file: {{ .Values.secure_env_file }}
  template:
    metadata:
      name: "{{ .Values.app.name }}-secret-{{ .Values.app.target_env }}"
      namespace: {{ .Values.app.namespace }}
    type: Opaque
---
######################################################
# Secret: Create Multiples encrypted data
######################################################
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ .Values.app.name }}-settings-{{ .Values.app.target_env }}"
  namespace: {{ .Values.app.namespace }}
spec:
  encryptedData:
    settings_sec_env_file: {{ .Values.settings_sec_env_file }}
  template:
    metadata:
      name: "{{ .Values.app.name }}-settings-{{ .Values.app.target_env }}"
      namespace: {{ .Values.app.namespace }}
    type: Opaque