apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc-{{ .Values.app.target_env }}
  labels:
    {{- include "dmz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "dmz.selectorLabels" . | nindent 4 }}
  externalIPs:
    - {{ .Values.app.custom_lb_svc_ip_addr }}
